name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # This workflow runs when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use a fresh Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Action to checkout your repository code

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Specify the Node.js version
        cache: 'npm' # Cache npm dependencies for faster builds

    - name: Install dependencies
      run: |
        rm -rf node_modules package-lock.json # Clean up old dependencies
        npm install --legacy-peer-deps # Install and update lock file

    - name: Update browserslist database
      run: |
        npx update-browserslist-db@latest

    - name: Build React app
      run: |
        CI=false npm run build # CI=false to ignore warnings as errors
      env:
        PUBLIC_URL: / # Set the PUBLIC_URL for proper asset paths

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
        publish_dir: ./build # Directory to publish
        cname: jarin.me # Your custom domain (should match your CNAME file)
